stages:
  - checks

test:
  stage: checks
  tags:
    - aave-build-runner
  before_script:
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml build
  script:
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml run contracts-env npm run ci:test
  after_script:
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml run contracts-env npm run ci:clean
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml down

deploy-mainnet-fork:
  tags:
    - aave-build-runner
  stage: checks
  before_script:
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml build
  script:
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml run contracts-env npm run aave:fork:main
  after_script:
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml run contracts-env npm run ci:clean
    - docker-compose -p ${CI_JOB_ID} -f docker-compose.test.yml down

certora-test:
  stage: checks
  image: python:latest
  before_script:
    - apt-get update || apt-get update
    - apt-get install -y software-properties-common
    - pip3 install certora-cli
    - wget https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
    - chmod +x solc-static-linux
    - mv solc-static-linux /usr/bin/solc
    - export PATH=$PATH:/usr/bin/solc/solc-static-linux
  script:
    - certoraRun specs/harness/StableDebtTokenHarness.sol:StableDebtTokenHarness --solc_args "['--optimize']" --verify StableDebtTokenHarness:specs/StableDebtToken.spec --settings -assumeUnwindCond,-b=4 --cache StableDebtToken --cloud
    - certoraRun specs/harness/UserConfigurationHarness.sol --verify UserConfigurationHarness:specs/UserConfiguration.spec --solc_args "['--optimize']" --settings -useBitVectorTheory --cache UserConfiguration --cloud
    - certoraRun contracts/protocol/tokenization/VariableDebtToken.sol:VariableDebtToken specs/harness/LendingPoolHarnessForVariableDebtToken.sol --solc_args "['--optimize']" --link VariableDebtToken:POOL=LendingPoolHarnessForVariableDebtToken --verify VariableDebtToken:specs/VariableDebtToken.spec --settings -assumeUnwindCond,-useNonLinearArithmetic,-b=4 --cache VariableDebtToken --cloud
